### ISSUE TITLE
The "Take back" button background is still disabled after move any figure

### ISSUE THREAD

**Issue by DarekRepos** [LabinatorSolutions/stockfish-chess-web-gui#31]
I caught one visual bug. I haven't attached any photo, but I record the steps to reproduce the error.

category: visual issue

severity: low

**Steps to reproduce:**

1. Open hosted "Web GUI For Stockfish Chess" app
2. Click the Engine toggle button ( switch "player" option )
3. Move any figure in any direction
4. Click the "take back" button

**Actual result:**

> The "Take back" button background is still disabled after moving any figure. The user  has switched the engine toggle button to "player" ( off setting). If user click the "Take back" he can still undo any move.

**Expected result:**

> When user click to move any figure the take out button change background from off (dark grey) to on (light grey)

Bug reproduced on Chrome and Edge browser

**Comment by LabinatorSolutions** [comment]
Thank you for reporting the bug!

**Comment by LabinatorSolutions** [comment]
Hello!

Thank you for your bug report. We have assigned you to fix this bug if you have time. Our team is highly occupied with other projects at the moment.

All the best!
