### ISSUE TITLE
Let change of level to Mobile players

### ISSUE THREAD

**Issue by rockcesar** [LabinatorSolutions/stockfish-chess-web-gui#35]
Hello, another proposed change. But as I have already openned a pull request, I recommend you to do it in a clean master branch, since the other changes are not accepted yet.

The change is in file js/board-actions-mobile.js line 51:

Add this line, before setTimeout:
updateEngineSkill();

It is to let change of level to Mobile players.

**Comment by LabinatorSolutions** [comment]
After the most recent update to the repository, I am not seeing this issue anymore. Please re-open this issue if you are still seeing it. Thank you!
